### PR TITLE
[JBIDE-26276] - intermittent test failures in webservices

### PR DESCRIPTION
**Pull request by jeffmaury**
- Add trace messages to better understand

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by nickboldt** [comment]
closing out of date

**Pull request closed without merging**
