### PR TITLE
JBIDE-24880: Split JAX-WS and JAX-RS plugins

### PR DESCRIPTION
**Pull request by rawagner**
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by rawagner** [comment]
plugins split to jax-ws and jax-rs
removed .classpath, .project, .settings files
general cleanup (removed unused files, replaced deprecated stuff etc)
removed jars in lib folder (jars are now dowloaded by maven)
cleaned up MANIFEST files
cleaned up features

**Comment by rawagner** [comment]
@jeffmaury  can you take a look ?

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by bdshadow** [comment]
looks like the build is fine, except the failing tests, that had been failing before too. I was also trying to fix them : https://github.com/jbosstools/jbosstools-webservices/pull/279, unfortunately, unsuccessfully

**Comment by nickboldt** [comment]
Any progress on this one? It's been a couple months... :(

**Comment by rawagner** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Pull request merged**
