### PR TITLE
Update publishing pattern

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Review by sbouchet — APPROVED** [review]
LGTM

**Comment by odockal** [comment]
@sbouchet How about the build failures?

**Comment by sbouchet** [comment]
was checking before being held by something else. that's why I did not merged the PR yet ...

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
3 tests failures as expected on both PR checks. can be merged

**Pull request merged**
