### PR TITLE
JBIDE-27716: fix build

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by sbouchet** [comment]
@odockal @jeffmaury i'm struggling to fix the unit test. also, the number of test/fialing differs from jenkins/Github actions.

**Comment by odockal** [comment]
@sbouchet I am also looking at it

**Comment by sbouchet** [comment]
only 3 test failing after my last push.
2 for quickfix
1 for deployTest 

almost done !

**Comment by odockal** [comment]
@sbouchet Yes I know! I guess that Unit test passing reference should be old jenkins job not GA. I guess I still have to figure out adding more jre runtime because I smell legacy unit tests...

**Comment by sbouchet** [comment]
deployTest seems to be flaky, and i cannot reproduce because I don"t have the correct EAP 4 to test with. 
looking at the two left items, I still tries to understand the quickfix code..

**Comment by sbouchet** [comment]
as seen with @jeffmaury ; this is blocking release right now so i'll merge as is and continue on tests after AM1.

**Comment by odockal** [comment]
@sbouchet Sure thing. Should be quick fix issue if not working at worst. Should not be a blocker. old be referenced in final sprint.

**Pull request merged**
