### PR TITLE
jbide-24076: [AERI] NPE in JaxrsApplicationCreationWizardPage.getWebxmlResource

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by jeffmaury** [comment]
@bdshadow how can we test it ?

**Comment by bdshadow** [comment]
@jeffmaury Create a simple Eclipse project (NOT Java project): File -> New -> Project -> Enter project name -> Finish. Right-click on the created project -> New -> Other... -> JAX-RS Application -> Choose "Defined in the web deployment descriptor" radio button - > Finish.
Without the fix it throws NPE, but does nothing with the fix as it is not a Java project

**Comment by jeffmaury** [comment]
@bdshadow does not work for me. I still got an NPE: see https://gist.github.com/jeffmaury/cc6540ee101c6679a9431df639c90260

**Comment by bdshadow** [comment]
Fixed NPE + changed the wizard a little bit, because project is used in both cases of creation of JAX-RS application. I know that elements are not properly aligned, but i wasn't able to fix it by now. It must be merged anyway, because the logic works fine now, and i'll create a new JIRA for ui fixes.
@jeffmaury please, take a look

**Pull request merged**
