### PR TITLE
JBDS-4133 - Upgrade to Lucene 5.4.1

### PR DESCRIPTION
**Pull request by xcoulon**
Due to org.jboss.tools.ws.jaxrs.core :: error occurred during JAX-RS Metamodel build:
java.lang.NoClassDefFoundError: org/apache/lucene/analysis/standard/StandardAnalyzer

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
TP changes to move to Lucene 5.4.1 (and keep 3.5.0, too) now building: https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/DevStudio/view/DevStudio_Master/job/jbosstoolstargetplatforms-matrix/ >= 598

**Comment by nickboldt** [comment]
testPR

**Comment by nickboldt** [comment]
Ran this PR locally after the switch to the AM3 TP with Lucene 5.4.1 and 3.5.0, and only one test suite failed: 

[INFO] org.jboss.tools.ws.creation.core.test .............. FAILURE [05:19 min]

**Comment by xcoulon** [comment]
@nickboldt @alexeykazakov I ran a build with the latest TP which now includes Lucene 5.4.1 and it was successful. Please let me know if this is the solution that we want to use to fix the compilation error problem.

**Comment by jeffmaury** [comment]
Closing as #256 has been selected during today's call

**Pull request closed without merging**
