### PR TITLE
Bumpup version to 2.0.201 in order to build component

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by sbouchet** [comment]
GH actions also fails on some tests (https://github.com/jbosstools/jbosstools-webservices/runs/1861508702#step:5:4934) 

the error  seems to be internet filure as the jenkins job shows correct output : 
```
[INFO] Fetching org.jboss.tools.ws.jaxrs.feature_2.0.200.v20200818-1644.jar from http://download.jboss.org/jbosstools/static/photon/stable/updates/core/4.18.0.Final/features/ (2.13kB)
[INFO] Fetching org.jboss.tools.ws.jaxrs.feature.source_2.0.200.v20200818-1644.jar from http://download.jboss.org/jbosstools/static/photon/stable/updates/core/4.18.0.Final/features/ (3.43kB)
```

**Comment by odockal** [comment]
@sbouchet Any idea what the cause to this error could be? Fetching jaxrs.features I have in mind... 
If I look at error: 
```
Error:  An error occurred while transferring artifact canonical: org.eclipse.update.feature,org.jboss.tools.ws.jaxws.feature,2.0.200.v20200918-1349 from repository http://download.jboss.org/jbosstools/static/photon/stable/updates/core/4.18.0.Final:
Error:     Unable to read repository at http://download.jboss.org/jbosstools/static/photon/stable/updates/core/4.18.0.Final/features/org.jboss.tools.ws.jaxws.feature_2.0.200.v20200918-1349.jar.
```

The referenced url returns 404.

**Comment by odockal** [comment]
@sbouchet the build ID is different from what builds requires and what is on update site: 
```
from build: org.jboss.tools.ws.jaxws.feature,2.0.200.v20200918-1349
vs.
What is on update site: org.jboss.tools.ws.jaxrs.feature.source_2.0.200.v20200818-1644.jar

**Comment by odockal** [comment]
retest

**Comment by odockal** [comment]
@sbouchet Can we merge this? I would then A rework workflows or B remove workflows and finish them locally.

**Comment by sbouchet** [comment]
@odockal: is version bumping necessary for this PR ? i already created another one that also bump version  (see #311 )

**Pull request closed without merging**
