### PR TITLE
jbide-25017: an attempt to fix tests

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by nickboldt** [comment]
Please fix the DCO issue by signing your commit. `git commit -s -m "JBIDE-25017 blah blah explanation goes here" .`

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
@bdshadow can you upversion in order to test the build

**Comment by bdshadow** [comment]
rebased

**Comment by jeffmaury** [comment]
@bdshadow can you upversion rebase is not enough

**Comment by nickboldt** [comment]
rebased and upversioned: https://github.com/jbosstools/jbosstools-webservices/pull/284

**Pull request closed without merging**
